- name: variables
  hosts: localhost
  vars: # variable declartion
    Course: "Terraform"
    Trainer: "Neela"
    Duration: "15HRS"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{ Course }} from Trainer {{ Trainer }}, Duration is {{ Duration }}."