- name: variables
  hosts: localhost
  vars: # variable declartion
    Course: "Ansible"
    Trainer: "Neela Reddy"
    Duration: "120HRS"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{ Course }} from Trainer {{ Trainer }}, Duration is {{ Duration }}."