- name: variables
  hosts: localhost
  vars: # variable declartion
    Course: "Ansible"
    Trainer: "Neela Reddy"
    Duration: "120HRS"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning Ansible to {{ Course }} and Neela Reddy to {{ Trainer }} and 120HRS to {{ Duration }}"