- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: Check user exists or not
    ansible.builtin.command: id expense
      ignore_errors: true
  - name: say Helllo
  ansible.builtin.debug:
    msg: "Hello"